name: Healthcheck

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00
        id: healthcheck
        with:
          url: https://full-stack-open-pokedex-1stk.onrender.com/
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false
          cookie: "token=asdf1234"
          basic-auth: "login:password"
      
      - name: app is alive
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ steps.healthcheck.conclusion == 'success' }}
        with:
          description: Web app is still alive https://full-stack-open-pokedex-1stk.onrender.com/
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      
      - name: app is dead
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ steps.healthcheck.conclusion == 'skipped' }}
        with:
          description: Web app is dead https://full-stack-open-pokedex-1stk.onrender.com/
          severity: error
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}