name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install start-server-and-test
        run: npm install start-server-and-test --save-dev
      #- name: Check style
      #  run: npm run eslint
      #- name: Jest test
      #  run: npm run test:unit
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # - name: Wait for application
      #   run: |
      #     while ! nc -z localhost 5000; do
      #       sleep 1
      #     done
      - name: Playwright Tests
        run: npm run test:e2e