name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"

      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      - name: print messages if they have clue word
        run: |
          messages=$(echo "${{ toJson(github.event.commits.*.message) }}" | sed 's/\[//g' | sed 's/\]//g' | sed 's/"//g')
          for message in $messages; do
            if [[ $message =~ \#skip ]]; then
              echo "there WAS word skip"
            fi
          done