name: Testing stuff
on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: success if there is word HI in the message
        id: message
        if: ${{ contains(join(github.event.commits.*.message, ' '), 'hi') }}
        run: echo "it WAS word HI in the message"
      
      - name: new version was deployed
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ steps.message.conclusion == 'success' }}
        with:
          text: A new version of Pokedex was deployed
          description: >
            **to https://full-stack-open-pokedex-1stk.onrender.com by ${{ github.event.commits[0].committer.username }}**
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
         
      - name: Build failed
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ steps.message.conclusion == 'skipped' }}
        with:
          text: Build failed
          description: >
           **commit ${{ github.event.commits[0].url }}\n
           by ${{ github.event.commits[0].committer.username }} broke the build**
          severity: error
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
