name: Testing stuff
on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: success if there is word HI in the message
        id: message
        if: ${{ contains(join(github.event.commits.*.message, ' '), 'hi') }}
        run: echo "it WAS word HI in the message"
      
      - name: new version was deployed
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ steps.message.conclusion == 'success' }}
        with:
          text: A new version of Pokedex was deployed
          #description: >
          #  **to https://full-stack-open-pokedex-1stk.onrender.com by ${{ github.event.commits[0].pusher }}**
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
         
      - name: Failure message to Discord
        uses: rjstone/discord-webhook-notify@89b0bf43c2c8514f70d0dcba4a706b904e8a3112
        if: ${{ steps.message.conclusion == 'skipped' }}
        with:
          text: A new version of Pokedex was deployed
          description: commit
          details: ${{ github.event.commits[0].url }}
          severity: error
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
