name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    env:
      COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
    steps:
      - uses: actions/checkout@v4

      - name: Commit messages
        run: echo "$COMMIT_MESSAGES"

      - name: print messages if they have clue word
        if: contains(join(fromJson('${{ toJson(github.event.commits.*.message) }}'), ' '), '#skip')
        run: echo "there WAS word skip"