name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: print messages if they have clue word
        if: contains(join(${{ env.COMMIT_MESSAGES }}, ' '), '#skip')
        run: echo "$COMMIT_MESSAGES"